<a href="https://colab.research.google.com/github/0Kyumy0/FirstCodes_DataScience/blob/Learning_Colaboratory/Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [ ]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [ ]:
distance = [100, 200, 400, 800, 1500, 3000, 5000, 10000]

In [ ]:
distance_array = np.array(distance)

3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [ ]:
print('The minimum distance is:', np.min(distance_array))
print('The maximum distance is:', np.max(distance_array))

The minimum distance is: 100
The maximum distance is: 10000


4) To find the average distance, use the np.mean() function

In [ ]:
print('The average distance is:', np.mean(distance_array))

The average distance is: 2625.0


5) use the np.sum() function to find the total distance

In [ ]:
print('The total distance is:', np.sum(distance_array))

The total distance is: 21000


6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [ ]:
np.cumsum(distance_array)

array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

7) To round all of the values in an array, use np.round()

In [ ]:
np.round(distance_array)

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [ ]:
time_array = np.array([10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45])

9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [ ]:
np.round(distance_array / time_array, 3)

array([9.416, 9.372, 8.29 , 7.053, 6.411, 5.923, 5.773, 5.69 ])

10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [ ]:
miles_equivalent = 0.00062
seconds_in_hour = 3600
distance_in_miles = np.array(((distance_array/time_array)*miles_equivalent)*seconds_in_hour)
print('The speed in milles per hour of the olympians is:' ,np.round(distance_in_miles, 3))
distance_in_miles = 75 - distance_in_miles
print('The diference in speed between a cheetah and each of the olympians is:', np.round(distance_in_miles, 3))

The speed in milles per hour of the olympians is: [21.017 20.918 18.504 15.742 14.31  13.219 12.884 12.7  ]
The diference in speed between a cheetah and each of the olympians is: [53.983 54.082 56.496 59.258 60.69  61.781 62.116 62.3  ]
