<a href="https://colab.research.google.com/github/0Kyumy0/FirstCodes_DataScience/blob/Learning_Colaboratory/NumPy_pasteleria.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

El precio de venta de 3 artículos en la venta de pasteles es: 2 por un brownie, 1 por una galleta y 10 por un pastel.

El club vende 17 brownies, 40 galletas y un pastel.

In [ ]:
import numpy as np

In [ ]:
price = [2, 1, 10]
quantity_sold = [17, 40, 1]

# se convierten las listas en arrays
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

### NOTA: Cálculo **elementwise** (elemento a elemento) ❗❗❗❗
La multiplicación se aplicó entre el primer elemento de cada 
array, y luego entre el segundo elemento de cada array, y así sucesivamente.  

In [ ]:
price_array * quantity_sold_array

array([34, 40, 10])

Costo de fabricación para cada elemento 0,25 para hacer un brownie, una galleta, 0,50 y un pastel, 5,00.

In [ ]:
cost_array = np.array([0.25, 0.50, 5.00])

In [ ]:
profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


Identificar qué elementos obtuvieron un beneficio superior a $2 por elemento. 

In [ ]:
profit_array > 2.00

array([False, False,  True])

Agreagamos el precio de un nuevo elemento: tarta con precio de 7

In [ ]:
# the proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


El club quiere agregar los siguientes precios: 4,50 por dulces, 3 por una magdalena, 4 por una barra de pan de plátano y 9 por una torta.  Al haber un valor flotante, convirtió a los demás en flotates.

In [ ]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [ ]:
# comprobar el tipo de elementos en la lista
print(price_array.dtype)

float64


Quieren eliminar el precio de la torta del array. 

In [ ]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


Después el club decide subir el precio de los pasteles de 10 a 12.

In [ ]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


# Orden


*   Brownies
*   Galletas
*   Pastel
*   Tarta
*   Dulces
*   Magdalenas
*   Pan de plátano









Actualizar la venta de 2 tartas, 3 bandejas de dulces, 16 magdalenas y 5 panes de plátano.  También se darán cuenta que una de las galletas que pensaron que se había vendido en realidad se cayó al suelo, así que editen quantity_sold_array de 40 a 39.  

In [ ]:
quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


Determinar la cantidad de dinero recaudado de la venta de cada elemento en la venta de la panadería.  

In [ ]:
total_sale = sum(quantity_sold_array * price_array)

Crear un array de NumPy "quantity_leftover" que incluya la cantidad de cada elemento restante al final de la venta: 2 pasteles, 1 tarta, 6 bandejas de dulces, 2 panes de plátano.  Pista: Asegúrense de incluir “0” de cada elemento que se haya vendido.


*   ¿Por qué esto es importante cuando se crea un array?

Porque si no se colocaran los elementos vendidos ("0"), alteraría el orden del array y los datos serían erroneos.

In [ ]:
quantity_leftover = [0, 0, 2, 1, 6, 0, 2]

In [ ]:
quantity_leftover_array = np.array(quantity_leftover)
print(quantity_leftover_array)

[0 0 2 1 6 0 2]


El club decide vender los elementos restantes a mitad de precio, y todo se venda rápidamente.  Determinen cuanto dinero se recaudó de la venta de liquidación.  

In [ ]:
total_sale_leftover = sum((quantity_leftover_array * price_array)/2)

¿Cuánto dinero total se recaudó de la venta de panadería (incluido la venta del precio total y los elementos liquidados)?

In [ ]:
total = total_sale + total_sale_leftover
print("The final total sale is: $", total)

The final total sale is: $ 213.5
